name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KEY }}

    - name: Deploy to server
      env:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        USERNAME: ${{ secrets.USERNAME }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST -p $PORT << 'EOF'
          cd $PROJECT_PATH
          git pull origin main
          source myenv/bin/activate
          pip install -r requirements.txt
          # 运行其他需要的部署命令，例如数据库迁移
          # python manage.py migrate
          # 重新启动机器人（根据你管理机器人的方式）
          # 例如，使用 systemd:
          # sudo systemctl restart mybot
        EOF
